// APP相关
export const SIDEBAR_TYPE = 'SIDEBAR_TYPE';
export const DEFAULT_COLOR = 'DEFAULT_COLOR';
export const DEFAULT_THEME = 'DEFAULT_THEME';
export const DEFAULT_FIXED_HEADER = 'DEFAULT_FIXED_HEADER';
export const DEFAULT_COLOR_WEAK = 'DEFAULT_COLOR_WEAK';
export const DEFAULT_LAYOUT_MODE = 'DEFAULT_LAYOUT_MODE';
export const DEFAULT_FIXED_HEADER_HIDDEN = 'DEFAULT_FIXED_HEADER_HIDDEN';
export const DEFAULT_CONTENT_WIDTH_TYPE = 'DEFAULT_CONTENT_WIDTH_TYPE';
export const DEFAULT_FIXED_SIDEMENU = 'DEFAULT_FIXED_SIDEMENU';
export const DEFAULT_DRAWER_BUTTON = 'DEFAULT_DRAWER_BUTTON';
export const DEFAULT_MULTIPLE_TABS = 'DEFAULT_MULTIPLE_TABS';

// user信息相关
export const SET_USER_ID = 'SET_USER_ID';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
