// APP相关
export const SIDEBAR_TYPE = 'SIDEBAR_TYPE';
export const DEFAULT_COLOR = 'DEFAULT_COLOR';
export const DEFAULT_THEME = 'DEFAULT_THEME';
export const DEFAULT_FIXED_HEADER = 'DEFAULT_FIXED_HEADER';
export const DEFAULT_COLOR_WEAK = 'DEFAULT_COLOR_WEAK';
export const DEFAULT_LAYOUT_MODE = 'DEFAULT_LAYOUT_MODE';
export const DEFAULT_FIXED_HEADER_HIDDEN = 'DEFAULT_FIXED_HEADER_HIDDEN';
export const DEFAULT_CONTENT_WIDTH_TYPE = 'DEFAULT_CONTENT_WIDTH_TYPE';
export const DEFAULT_FIXED_SIDEMENU = 'DEFAULT_FIXED_SIDEMENU';
export const DEFAULT_DRAWER_BUTTON = 'DEFAULT_DRAWER_BUTTON';
export const DEFAULT_MULTIPLE_TABS = 'DEFAULT_MULTIPLE_TABS';

// user信息相关
export const SET_USER_ID = 'SET_USER_ID';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';

// change信息相关
export const GET_TASK_TABLE = 'GET_TASK_TABLE';
export const SET_TASK_TABLE_PAGE = 'SET_TASK_TABLE_PAGE';
export const SET_TASK_LIST = 'SET_TASK_LIST';
export const SET_TASK_LIST_PAGE = 'SET_TASK_LIST_PAGE';
export const SET_TASK_VALUE = 'SET_TASK_VALUE';
export const SET_DASH_BUTTON = 'SET_DASH_BUTTON';
export const SET_CHANGE_INFO = 'SET_CHANGE_INFO';

// publish信息相关
export const SET_TASK_INFO = 'SET_TASK_INFO';
export const SET_PUBLISH_BUTTON = 'SET_PUBLISH_BUTTON';
export const SET_PUBLISH_TAB = 'SET_PUBLISH_TAB';
export const SET_PUBLISH_PROCESSING = 'SET_PUBLISH_PROCESSING';

// service 信息相关
export const ONE_LEVEL_CATALOG = 'ONE_LEVEL_CATALOG';
export const TWO_LEVEL_CATALOG = 'TWO_LEVEL_CATALOG';
export const THREE_LEVEL_CATALOG = 'THREE_LEVEL_CATALOG';
export const ONE_DIRECTORY = 'ONE_DIRECTORY';
export const TWO_DIRECTORY = 'TWO_DIRECTORY';
export const THREE_DIRECTORY = 'THREE_DIRECTORY';
export const SET_SERVICE_INFO = 'SET_SERVICE_INFO';
export const SET_SERVICE_PROCESSING = 'SET_SERVICE_PROCESSING';
export const SET_SERVICE_TASK = 'SET_SERVICE_TASK';
export const SET_TWO_OBJECT = 'SET_TWO_OBJECT';
